### ISSUE TITLE
SharedInformer and API

### ISSUE THREAD

**Issue by sbezverk** [ligato/networkservicemesh#115]
When k8s Informer informs about k8s object deletion, it does not provide the actual object as in the case of object creation, instead it returns `name/namespace`. Normally it would be sufficient but with proposed API, delete method is called with the object.

```
type API interface {
	ObjectCreated(obj interface{})
	ObjectDeleted(obj interface{})
	ObjectUpdated(objOld, objNew interface{}) 
```

In order preserve this API model, prior to calling ObjectDeleted, a type of deleted object needs to be deduced and only then ObjectDeleted should be called with this object type.

It can be done by switching back to per object type Informer, in this case we will know implicitly the type of object.
For the SharedInformer case,  ObjectDeleted should be changed to string, but it will be impossible to guess the type of object.

WDYT?

**Comment by edwarnicke** [comment]
How does someone look up an Object?

Ed

**Comment by sbezverk** [comment]
@edwarnicke for deleted object, there is no way to find out other than `if delete message came from Informer of objects type A then it was object of type A`
For Shred informers it will not work.

**Comment by edwarnicke** [comment]
@sbezverk My question was more: I presume we are storing the Objects so someone else can look them up.  How does someone look up an Object?

**Comment by sbezverk** [comment]
@edwarnicke Got it. 
```
func (p *Plugin) ObjectCreated(obj interface{}) {
	p.Log.Infof("ObjectStore.ObjectCreated: %s", obj)

	switch obj.(type) {
	case netmesh.NetworkService:
		ns := obj.(netmesh.NetworkService)
		p.Objects.NetworkServicesStore.Add(&ns)
	case netmesh.NetworkServiceEndpoint:
	case netmesh.NetworkService_NetmeshChannel:
	}
}
```

Let me know if it answers your question.

**Comment by edwarnicke** [comment]
@sbezverk Ah, I misunderstood... this is the SPI for callbacks :)

**Comment by mestery** [comment]
I see the issue here now, and I think we need to move back to per-object informers so we can provide the object to our handler API on delete.
