### ISSUE TITLE
NSM needs a mascot

### ISSUE THREAD

**Issue by lixuna** [ligato/networkservicemesh#164]
Brainstorming ideas in July 13, 2018 NSM meeting: 

- tunnel spider
- something that will look great as a plush, stuffed animal
- something alive preferred
- doesn't have to be an animal
- something switching connections (like telephones)
- 90's - Teenage Mutant Ninja Turtles - Master Splinter

**Comment by lixuna** [comment]
Ideas on July 20, 2018 NSM meeting: 

Ed has been using Adriane the NSM spider in presentation: https://docs.google.com/presentation/d/1IC2kLnQGDz1hbeO0rD7Y82O_4NwzgIoGgm0oOXyaQ9Y/edit#slide=id.g3e2fecab4e_0_292

**Comment by lixuna** [comment]
Name:  Ariadne

Associated with mazes and labyrinths

**Comment by fkautz** [comment]
Marking this as complete. We have more work to do in regards to branding. Some of these tasks will happen once we work out where NSM will live.
