### ISSUE TITLE
L2 forwarding with VPP example

### ISSUE THREAD

**Issue by fkautz** [ligato/networkservicemesh#185]
- [ ] Create L2 forwarding example
- [ ] Document the example

**Comment by tfherbert** [comment]
I apologize in advance for "hijacking this issue" but after discussing with @fkautz I think  this matches closely what I have in mind and I will take this on. If the below is not what was initially intended, please comment.
Plan:
Introduction:
Implement  VPP example NSE as an L2 provider. Plan to use memif initially. Demonstrate by forwarding traffic "through" the pod via the L2 IF.
1. Define protocol extension to specifiy additional configuration of the L2 connection of what we may call an NSM extended endpoint.
2. Construct a sidecar that will perform the inject action by building the L2 forwarder.

**Comment by tfherbert** [comment]
I am currently working on this.

**Comment by tfherbert** [comment]
@fkautz This is a note that @tfherbert is working on this pull request.

**Comment by lixuna** [comment]
We have an example, ticket can be closed

**Comment by lixuna** [comment]
to be assigned to therbert

**Comment by edwarnicke** [comment]
Some helpful hints:

* [vppagent L2 API](https://github.com/ligato/vpp-agent/blob/v1.7/plugins/vpp/model/l2/l2.proto)
* [BridgeDomain.Interface.Name](https://github.com/ligato/vpp-agent/blob/v1.7/plugins/vpp/model/l2/l2.proto#L18) should match [Interfaces.Interface.Name](https://github.com/ligato/vpp-agent/blob/v1.7/plugins/vpp/model/interfaces/interfaces.proto#L25)
* [vppagent-icmp-responder-nse](https://github.com/ligato/networkservicemesh/tree/master/examples/cmd/vppagent-icmp-responder-nse) shows a good example of a NSE that Terminates an Connection on a vppagent running in the same container.  One thing to watch for is you probably *don't* want a dst_ip as its a bridge domain.
* You can simply copy the stock [nsc.yaml](https://github.com/ligato/networkservicemesh/blob/master/k8s/conf/nsc.yaml) and change the [NETWORK_SERVICES](https://github.com/ligato/networkservicemesh/blob/master/k8s/conf/nsc.yaml#L24) env variable.

**Comment by tfherbert** [comment]
Ed, Thanks.
