### ISSUE TITLE
Publish images to docker hub

### ISSUE THREAD

**Issue by fkautz** [ligato/networkservicemesh#186]
NSM images should be published to the docker repo on every successful merge in master.

**Comment by fkautz** [comment]
If there is no easy way to do this from Travis, we can trigger a build in docker hub.

**Comment by mestery** [comment]
I'll take a peek at this one, I think I can get something pushed out relatively quickly to make this work.

**Comment by lixuna** [comment]
7/27/2018: ETA early next week

**Comment by mestery** [comment]
Actually, I have another plan to revive the travis method after discussing with @sbezverk so I'll propose that patch later this afternoon.
