### ISSUE TITLE
Stop relying on $HOSTNAME to identify the pod

### ISSUE THREAD

**Issue by fkautz** [ligato/networkservicemesh#195]
Hostnames can be set in the pod's spec. They are not capable of reliably identifying the current pod's metadata name or differentiating an eNSM from another.

Find all instances of HOSTNAME and exorcise them unless that specific instance really does need a host name.

**Comment by lixuna** [comment]
Points to note (@edwarnicke): 

- we’d like the NSM to be as easy to use as possible, 
- External network services may be a future use case

Problem (@fkautz):
- HOSTNAME is a settable variable in pod spec
- if HOSTNAME is not set, this approach may not work

Goal: 
- to have a reference to match

Options:
- have an NSM agent on each node
- use pod name and namespace id
- run FS notifier, watch files for namespace

**Comment by fkautz** [comment]
There are currently three commands still relying on HOSTNAME:

* cmd/nsm-generate-sriov-configmap/nsm-generate-sriov-configmap.go
* cmd/nsm-init/nsm-init.go
* plugins/nsecommand/impl.go

**Comment by nickolaev** [comment]
The only remaining occurrence of this is in `examples/cmd/nsm-generate-sriov-configmap/nsm-generate-sriov-configmap.go`, which being an example is not that bad. Is this one still valid?
