### ISSUE TITLE
Check out SR-IOV on packet.net

### ISSUE THREAD

**Issue by fkautz** [ligato/networkservicemesh#197]
Ian Wells checked out whether SR-IOV support is available. Support appears to be present.

We may need to ask packet.net to enable in BIOS for a given instance.

- [ ] Determine if we can set BIOS SRIOV settings on demand
- [X] Check for SR-IOV support on Mellanox system (thanks Ian)
- [ ] Check for SR-IOV support on Intel based system
- [ ] Determine if we can break down NIC on single NIC system

**Comment by fkautz** [comment]
Ian mentioned we can break the NIC down on a c1.medium.x86 to 8 VFs.

**Comment by fkautz** [comment]
I am going to email packet support to see if we can configure BIOS on-demand to enable SR-IOV

**Comment by taylor** [comment]
@fkautz, regarding task " Determine if we can break down NIC on single NIC system". 

Is this for the bonded NICs?  If so the answer is yes.

/cc @michaelspedersen

**Comment by lixuna** [comment]
Reference: https://github.com/ligato/networkservicemesh/wiki/Experiences-running-hardware-tests-using-packet.net

**Comment by lixuna** [comment]
@taylor had a thread with packet discussing support for SR-IOV

**Comment by lixuna** [comment]
8/10/2018 Current status: 
- Having problems with Mellanox NICs

**Comment by lixuna** [comment]
8/10/2018 Next steps: 
 - @taylor will request systems from packet for NSM to use

**Comment by michaelspedersen** [comment]
The email I got about the mention was caught in junk-filter (...)
But I can confirm Mellanox SR-IOV works. For use with VPP I had to downgrade to VPP 18.04 (DPDK 18.02.1)

Regarding "Determine if we can break down NIC on single NIC system", I think Packet usually bonds two ports for the primary NIC. It is possible to remove one of the interfaces: https://help.packet.net/technical/networking/layer-2-configurations

**Comment by lixuna** [comment]
8/24/2018 update from Taylor:

- Intel NICs are an available option
- Packet does not have available ConnectX-5 for us at this time

8/24/2018 update from Ed: 

- CNX-4 should work with VPP 
- there's an issue with latest drivers that appear to be broken

Next steps:
- Document specs for software install 
- Check with Michael P. on progress made on this

**Comment by michaelspedersen** [comment]
"Determine if we can break down NIC on single NIC system"
- This should definitely be possible (see layer-2-config link in previous message). I had VFs created and saw traffic between VFs, but not tested across multiple instances (e.g. using VLANs)

"Check for SR-IOV support on Intel based system"
- Haven't tested this out on Packet instances yet, but I don't see why this wouldn't work. If anything we can do a simple test using two of the x1.small.x86 instances as they have 10G connectivity via a x710 NIC

"Determine if we can set BIOS SRIOV settings on demand"
- This one depends on what is accessible via the Packet user portal. If there is a management controller (CIMC, ILO etc.) it can be configured via that. I know CIMC allows for configuration through the host OS, but I doubt that is available for Packet instances

**Comment by fkautz** [comment]
I believe this has been well explored, conclusion is VPP should be able to use this when new version is out.
