### ISSUE TITLE
[Proposal] Allow only squash commits

### ISSUE THREAD

**Issue by fkautz** [ligato/networkservicemesh#219]
GitHub allows us to control the types of commits we can perform in the project. I recommend we use the following settings:

- [ ] Allow merge commits - Add all commits from the head branch to the base branch with a merge commit.
- [X] Allow squash merging - Combine all commits from the head branch into a single commit in the base branch.
- [ ] Allow rebase merging - Add all commits from the head branch onto the base branch individually.

The reason for disabling merge and rebase is two fold:

* Intermediate states representing work in progress would not be present in the repo, making history easier to read
* Easier to find defects via git bisect since only states that pass the build are merged in.

Any preferences or comments?

**Comment by edwarnicke** [comment]
+1

**Comment by sbezverk** [comment]
+1

**Comment by mestery** [comment]
+1

**Comment by fkautz** [comment]
This is now implemented.
