### ISSUE TITLE
Fix CRD code to autogenerate OpenAPI validations from the protobuf files

### ISSUE THREAD

**Issue by mestery** [ligato/networkservicemesh#277]
Currently we were hand coding these. While the Kubernetes code does not have the direct capability to autogenerate OpenAPI models yet, there is some work available to do this.

Specifically, we'll do the following:

- statically generate openapi_spec (with references) using: https://github.com/kubernetes/kube-openapi:
- Call https://github.com/ant31/crd-validation/blob/master/pkg/crdvalidation.go#L39:

**Comment by sbezverk** [comment]
AFAIK in k8s all validations are done either in go code for core API types, see here: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go
or via static OpenAPI  for the case of CRD. There is another way to do validation is via webhooks, but I am not sure if the complexity of webhook solution is justified here. 
What is the main driver to get validation dynamic?
