### ISSUE TITLE
Remove channels

### ISSUE THREAD

**Issue by mestery** [ligato/networkservicemesh#283]
Per discussion in the 2018.09.07 team meeting, we'll remove Channels from the code and instead rely on a NetworkService having a payload type. Channels ended up being redundant.

**Comment by mestery** [comment]
@edwarnicke Currently our external API is defined as follows:

```
message NetworkServiceChannel {
    common.Metadata metadata = 1;
    string network_service_name = 2;
    string nse_provider_name = 3;
    string payload = 4;
    string socket_location = 5;
    repeated common.Interface interface = 6;
}

message NetworkServiceEndpoint {
    common.Metadata metadata = 1;
}

message NetworkService {
    common.Metadata metadata = 1;
    repeated NetworkServiceChannel channel = 2;
}
```

Is the idea to remove Channels as a separate message and put them inside of the NetworkService message, something like this:

```
message NetworkServiceEndpoint {
    common.Metadata metadata = 1;
}

message NetworkService {
    common.Metadata metadata = 1;
    message NetworkServiceChannel {
        string network_service_name = 1;
        string nse_provider_name = 2;
        string payload = 3;
        string socket_location = 4;
        repeated common.Interface interface = 5;
    }
    repeated NetworkServiceChannel channel = 2;
}
```

Currently we have a list of those in the NetworkService object, so if we just want to remove Channels as n explicit part of the API, this would do it.

Curious on your and @sbezverk thought's here.

**Comment by sbezverk** [comment]
@mestery I think actually changing proto file is not even required. What we do not need (imho) is having NetworkChannels as a separate item n out types.go and also in CRD controller.

**Comment by mestery** [comment]
@sbezverk That's fine, but now our external API will expose Channels, but the CRDs won't. It wasn't clear to me that was the intention here. In other words, via CRDs we can no longer create Channels, but via the external API (over gRPC) we can. Is that ok?

**Comment by edwarnicke** [comment]
I think what I had in my mind when we discussed this was closer to:

```
message NetworkService {
    common.Metadata metadata = 1;
    string name = 2;
    string payload = 3;
}
```
Network service becomes very simple.

Then Network Service Endpoint picks up some slack:

```
message NetworkServiceEndpoint {
    common.Metadata metadata = 1;
    string network_servivce_name = 2;
    ... - stuff which we should hash out that lets us identify the NSM handling this NSE, how to reach it, and how to tell it which NSE we want.
}
```

Thoughts?

**Comment by sbezverk** [comment]
@edwarnicke while working on nse example I had to built a separate message. Please see this file:
https://github.com/ligato/networkservicemesh/blob/master/pkg/nsm/apis/nseconnect/nseconnect.proto
Actually nse proto definitions use channel message. So it needs to stay and stay as a separate message.

**Comment by fkautz** [comment]
My opinion is we should remove channels throughout the entire system. No reason to keep them in even if they are hidden from the user. Also, assume our proto definitions will be a public api and people will consume them to build nse, ensm and pnsm.

**Comment by sbezverk** [comment]
What do you think about these 2 API Objects:
```
message NetworkServiceEndpoint {
    common.Metadata metadata = 1;
    string network_service_name = 2;
    string network_service_host = 3;
    string nse_provider_name = 4;
    string payload = 5;
    string socket_location = 6;
    repeated common.Interface interface = 7;
}

message NetworkService {
    common.Metadata metadata = 1;
}
```
NetworkServiceEndpoint describes a LOCAL to the host network service and NetworkService a cluster wide advertisement of a network service. Association between NSE and NS are done only by means of labels.

WDYT?

**Comment by sbezverk** [comment]
Flow of request:
Client requests NS Bridge1 and client supports vxlan tunnel:
1. NSM checks all NSE advertised support for service Bridge1
2. Selectint the one supporting vxlan tunnel
3. If found, client's local NSM communicates with NSE local NSM to build connection
4. if intermediary connection is success, client gets confirmation.

**Comment by edwarnicke** [comment]
@sbezverk When you say client, do you mean the Pod that has requested a connection to NS Bridge1?  Or the NSM trying to set up the cross-connect for that Pod?

**Comment by sbezverk** [comment]
@edwarnicke client POD which requires NS Bridge1. At this point I am trying to trace initial signalling part.

**Comment by edwarnicke** [comment]
@sbezverk OK... so the Pod which needs NS Bridge1... it needs a local mechanism (kernel interface, memif, vhost user, etc)... not a remote mechanism (VXLAN).   I would suggest the flow more like this:

1.  Pod sends Request Connection to its loca NSM (NSM1), specifying a preference list of local mechanisms (things like kernel interface, memif, vhost user, etc)
2. NSM1 checks all NSEs advertising support for Network Service Bridge1.
3. NSM1 selects one of those NSEs, which is handled by NSM2
4. NSM1 communicates with NSM2 to build the connection, NSM1 and NSM2 agree on a remote mechanism (things like VXLAN, GRE, etc)
5.  NSM2 of course is also talking to its local NSE, and negotiating a local mechanism for the connection)
6.  NSM2 sets up its end of the cross connect, including connecting the local mechanism to the NSE, and cross connecting that local mechanism to its end of whatever tunnel.
7.  NSM1 does likewise.

Does this make sense?
Parts of it are in pictures here: https://docs.google.com/presentation/d/1IC2kLnQGDz1hbeO0rD7Y82O_4NwzgIoGgm0oOXyaQ9Y/edit#slide=id.g3e2fecab4e_2_660

But what is not in that picture is the contents of what goes in the various API calls and CRDs.
