### ISSUE TITLE
 sriov-controller is not built

### ISSUE THREAD

**Issue by pkdas** [ligato/networkservicemesh#297]
Can you please add sriov-controller build and its docker image build?
Now I have modify every time the Makefile and do a sriov-controller build manually.

Thanks

**Comment by sbezverk** [comment]
@pkdas One of the reason we do not publish sriov-controller image is because it is not being tested by our CI. Once we have CI up with sriov support, we will add building sriov-controller images.
@mestery Am I on the right track?

**Comment by pkdas** [comment]
You can still provide a script to build sriov-controller.   SR-IOV requires HW/NIC support I am not sure if you can automate testing without the HW. 

If you are saying SR-IOV controller is still very much work in progress and is being designed, then it is ok not to include in the build.

I am trying to compare the MULTUS-CNI, SRIOV-CNI and SRIOV-network-device plugin with  NSM way of doing things.
