### ISSUE TITLE
Update both Minikube and Kubernetes version in CI

### ISSUE THREAD

**Issue by mestery** [ligato/networkservicemesh#311]
[Minikube v0.29.0](https://github.com/kubernetes/minikube/blob/v0.29.0/CHANGELOG.md) is out now, and it adds support for additional kubernetes versions, so we should try using this version in the CI.

**Comment by edwarnicke** [comment]
Is this issue still really open?

**Comment by mestery** [comment]
It was just opened 3 days ago, and I haven't pushed a PR yet, so yes. :)
