### ISSUE TITLE
VPP Dataplane: VXLAN Mechanism

### ISSUE THREAD

**Issue by edwarnicke** [ligato/networkservicemesh#342]
This issue is to integration the memif mechanism into the vpp dataplane:

https://github.com/ligato/networkservicemesh/tree/master/dataplanes/vpp

I'll add a sequence of comments here to explain things that are helpful to understand of think about to accomplish this goal.

**Comment by edwarnicke** [comment]
# The K8s NSM Dataplane API

The [K8s NSM Dataplane API](https://github.com/ligato/networkservicemesh/blob/master/pkg/nsm/apis/dataplaneinterface/dataplaneinterface.proto) fundamentally is about Creating and Destroying [Connections](https://github.com/ligato/networkservicemesh/blob/master/pkg/nsm/apis/dataplaneinterface/dataplaneinterface.proto#L21).  A Connection has a [local_source](https://github.com/ligato/networkservicemesh/blob/master/pkg/nsm/apis/dataplaneinterface/dataplaneinterface.proto#L22) that is a [LocalMechanism](https://github.com/ligato/networkservicemesh/blob/master/pkg/nsm/apis/common/common.proto#L31) that has a [Type](https://github.com/ligato/networkservicemesh/blob/master/pkg/nsm/apis/common/common.proto#L36) and [parameters](https://github.com/ligato/networkservicemesh/blob/master/pkg/nsm/apis/common/common.proto#L33). parameters are simply a map<string,string>.

A Connection also has a [destination](https://github.com/ligato/networkservicemesh/blob/master/pkg/nsm/apis/dataplaneinterface/dataplaneinterface.proto#L23) that is either a [LocalMechanism](https://github.com/ligato/networkservicemesh/blob/master/pkg/nsm/apis/common/common.proto#L31) or a [RemoteMechanism](https://github.com/ligato/networkservicemesh/blob/master/pkg/nsm/apis/common/common.proto#L45).  A RemoteMechanism has a [type](https://github.com/ligato/networkservicemesh/blob/master/pkg/nsm/apis/common/common.proto#L50) and [parameters](https://github.com/ligato/networkservicemesh/blob/master/pkg/nsm/apis/common/common.proto#L47) which are a map<string,string>.   Like a LocalMechanism, a RemoteMechanism may be fully or partially specified.  A partially specified RemoteMechanism contains some but not all of its required parameters, or hints about those parameters.  A fully specified RemoteMechanism contains all of the required parameters.

VXLAN is a RemoteMechanism.  It has parameters:

* src_ip - src_ip of the tunnel
* dst_ip - dst_ip of the tunnel
* vni - vni of the tunnel

It may also have a parameter
* vnis - a list of ranges of acceptable vni values.  Example: "vnis=1-20,100-500".  This is used by the dataplane to communicate the list of vni's which the NSM can offer to its peer to be selected amongst.

When a VXLAN RemoteMechanism is reported back to the NSM by MonitorMechanism (upcoming rename for [UpdateDataplane](https://github.com/ligato/networkservicemesh/blob/master/pkg/nsm/apis/dataplaneinterface/dataplaneinterface.proto#L16).  It should have parameters src_ip and vnis.  src_ip should be a src_ip available on the dataplane for use for vxlan tunnels, and vnis the list of ranges of vnis available for use for tunnels.

**Comment by edwarnicke** [comment]
# Manipulating VPP VXLAN tunnels via CLI

We will be programming memif using the Go language bindings, but it helps tremendously to be able to manipulate it via the CLI for purposes of debugging and trial and error.

VPP provides a command

```
vppctl ${cmd}
```

If vpp is running in a docker container:

```
docker exec ${dockerid} vppctl ${cmd}
```

The [cli commands related to vxlan](https://docs.fd.io/vpp/18.07.1/clicmd_src_vnet_vxlan.html).
Note: for our case we will mostly be creating and deleting vxlan tunnels.

If you wish to try to drive the api via the CLI:

```
vppctl bin help
```

lists the API

```
vppctl bin help ${api} 
```

gives specific

```
vppctl bin ${api} ${api parameters}
```
calls the api.

**Comment by edwarnicke** [comment]
# Programming VPP VXLAN via GO

The VPP Go API for [VXLAN is already in the repo])(https://github.com/ligato/networkservicemesh/blob/master/dataplanes/vpp/bin_api/vxlan/vxlan.ba.go).

**Comment by edwarnicke** [comment]
# Overall Cross Connects

Implementation of the vxlan mechanism means also implementing its cross connect to:
1. memif
2. kernel interface

You should be able to use the same l2 cross connect logic already done in the code base for cross connecting two kernel interface mechanisms.

**Comment by edwarnicke** [comment]
# Where to start in the VPP Dataplane

[ConnectionRequest](https://github.com/ligato/networkservicemesh/blob/master/pkg/nsm/apis/nsmconnect/nsmconnect.proto#L8) is [implemented in the VPP Dataplane](https://github.com/ligato/networkservicemesh/blob/master/dataplanes/vpp/pkg/nsmdataplane/nsmdataplane_server.go#L67).  This is probably the best place to start in the Dataplane.

**Comment by edwarnicke** [comment]
This issue relies on Issue #343 to be fully testable.

**Comment by nickolaev** [comment]
@platoff are you actively working on this issue? Do you have already some WIP branch which you can share?

**Comment by edwarnicke** [comment]
@nickolaev Some pointers that may help here.

1.  The places this would drop into the code are here:
https://github.com/ligato/networkservicemesh/blob/master/dataplane/vppagent/pkg/converter/remote_connection_converter.go
2.  Don't forget to tell the dataplane to advertise here: https://github.com/ligato/networkservicemesh/blob/master/dataplane/vppagent/pkg/vppagent/vppagent.go#L47
3. Constants for keys for Parameters should go in a constants.go here:
https://github.com/ligato/networkservicemesh/tree/master/controlplane/pkg/apis/remote/connection
4. You'll want to fill out the validation here:
https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/apis/remote/connection/helpers.go

(see example of validation here: https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/apis/local/connection/helpers.go )

There's another interesting point, which is how the Dataplane gets its src_ip.  There are lots of ways it can be done.  The industrial state version of which would be for your Dataplane to own a physical NIC on the Node with a permanent globally routable IP.  All of that said, I expect for a first pass, we will likely use the Dataplanes Pod IP address, but am open to other thoughts :)

**Comment by edwarnicke** [comment]
[show vxlan tunnel](
https://docs.fd.io/vpp/18.10/clicmd_src_vnet_vxlan.html#clicmd_show_vxlan_tunnel)

Can be run via vppctl to see all tunnels during dev.,

**Comment by nickolaev** [comment]
@edwarnicke I believe this one can be closed now.
