### ISSUE TITLE
Shellcheck issues warning when running on circle-ci

### ISSUE THREAD

**Issue by mestery** [ligato/networkservicemesh#345]
This is seen in circle-ci logs (see [here](https://circleci.com/gh/ligato/networkservicemesh/193?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) for an example):

```
#!/bin/bash -eo pipefail
make check dep-check
shellcheck: unable to decommit memory: Invalid argument
```

[This](https://github.com/koalaman/shellcheck/issues/785) GitHub issue seems to track this. It appears innocuous, but we may want to install a newer shellcheck or build it ourself to avoid this warning.

**Comment by platoff** [comment]
Installing spellcheck stable (0.5.0) solves the issue. https://github.com/ligato/networkservicemesh/pull/327/files#diff-dc2f19473ed2123d5ba8b6fa9cb89383

**Comment by edwarnicke** [comment]
Should this issue be closed now?

**Comment by platoff** [comment]
I think it's fixed, would be happy to close but do not have permissions.
