### ISSUE TITLE
Access to github NSM issues

### ISSUE THREAD

**Issue by tfherbert** [ligato/networkservicemesh#370]
Add ability to edit issues assigned by others.
Add your github ID below:
Git Hub ID  -- Name -- Company
tfherbert -- Thomas F Herbert -- Red Hat

**Comment by taylor** [comment]
@taylor - Taylor Carpenter - Vulk Coop

**Comment by edwarnicke** [comment]
@taylor @tfherbert You should both have an invite to get read access (which is the same access the general public has... but give just enough hint to GitHub to let issues be assigned to you :) )

**Comment by nickolaev** [comment]
@nickolaev -- Nikolay Nikolaev -- VMware

**Comment by edwarnicke** [comment]
I think there are invites out to everyone on this list. Closing.
