### ISSUE TITLE
ci/circleci: packet-deploy is not stable

### ISSUE THREAD

**Issue by mestery** [ligato/networkservicemesh#415]
I've seen two PRs recently fail the `ci/circleci: packet-deploy` CI build when they pass the travis-ci builds. They each appear to be related to packet.net somehow. The failures are for these PRs:

- #380 
- #413 

I haven't looked at other recent builds, but these two caught my eye.

**Comment by taylor** [comment]
Related cross-cloud issue https://github.com/crosscloudci/cross-cloud/issues/171

**Comment by edwarnicke** [comment]
We seem to have super stable packet.net deploy now.  Closing issue :)
