### ISSUE TITLE
Implement remote.NetworkServiceServer/Client in nsmd

### ISSUE THREAD

**Issue by edwarnicke** [ligato/networkservicemesh#507]
In order to enable nsmd's on different Nodes to communicate to set up remote.Connection between them, we will need nsmd to implement both a

[remote.NetworkServiceServer](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/apis/remote/networkservice/networkservice.pb.go#L146)

and a 

[remote.NetworkServiceClient](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/apis/remote/networkservice/networkservice.pb.go#L114)

based on the [remote/networkservice/networkservice.proto](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/apis/remote/networkservice/networkservice.proto)

**Comment by edwarnicke** [comment]
== Changes to controlplane/pkg/nsmd/network_service_server.go NSE lookup ==

[controlplane/pkg/nsmd/network_service_server.go](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/nsmd/network_service_server.go) currently only handles NSEs that are local to and managed by that nsmd.

The simplest (and most immediate) fix for this is to replace the:

[endpoints := srv.model.GetNetworkServiceEndpoints(request.GetConnection().GetNetworkService())](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/nsmd/network_service_server.go#L53) call with a call the [registryFindNetworkService](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/apis/registry/registry.proto#L54).

**Comment by edwarnicke** [comment]
## remote.NetworkService.Request from remote nsmd

Handling non-local NSEs would go [here](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/nsmd/network_service_server.go#L154).  

First you would want to call [remote.NetworkService.Request](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/apis/remote/networkservice/networkservice.proto#L34).

The [remote.Connection](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/apis/remote/connection/connection.proto#L42) should be partially specified.

Partially specified in this case means:
1.  No Connection.Id.  The remote nsmd should fill in the Connection.Id
2. If using something like a VXLAN Mechanism, src_ip would be specified, but not dst_ip or vni. (see #342 )

Please note: remote.Connection once fully completed by the remote nsmd and returned to the local nsmd will match in both nsmds.  It will have the same remote.Connection.Id and content.

You can then use the Connection returned from the remote nsmd to program the CrossConnect for the Dataplane.

I would suggest doing this initially as a simple standalone PR, though doubtless it will need to be revisited when the server side is complete.

**Comment by fkautz** [comment]
I recommend these end up in a new project board in github. 

https://github.com/ligato/networkservicemesh/projects

**Comment by edwarnicke** [comment]
@fkautz https://github.com/ligato/networkservicemesh/projects/2

**Comment by edwarnicke** [comment]
@haiodo You had asked about the server implementation for registry.FindNSE()... 

its in the [nsmd-k8s](https://github.com/ligato/networkservicemesh/blob/master/k8s/pkg/registryserver/nse.go#L96).

You can reach it the same way we do for [registering NSEs in the nsmd](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/nsmd/registry.go#L40)

It might be worth simply doing a DiscoveryClient() func similar to [RegistryClient()](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/nsmd/registryclient.go#L36).

**Comment by haiodo** [comment]
Ok, It seems I've found all stuff I need.

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/477235/48789086-d6012080-ed1e-11e8-809b-77a7f96bcfd0.png">

Just one question left:
https://github.com/ligato/networkservicemesh/blob/e7755545a47f8c6aefce97536a85fdf98d799089/controlplane/pkg/nsmd/workspace.go#L82
Register NetworkServiceManager and URI is always same, nsmUrl := "127.0.0.1:5000" it is set at https://github.com/ligato/networkservicemesh/blob/e7755545a47f8c6aefce97536a85fdf98d799089/controlplane/cmd/nsmd/nsmd.go#L16

Any idea how to make it a proper one? Thanks.

**Comment by edwarnicke** [comment]
Ah... good catch.

So the nsmdpapi should only listen on "127.0.0.1:5000" and the nsmUrl should involve the IP address of the Pod.

**Comment by edwarnicke** [comment]
I suspect you will find yourself wanting to store Connection state... when you get to that point, you should consider simply using [remote.MonitorConnectionServer](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/remote/monitor_connection_server/monitor_connection_server.go#L44) to do so.  It handles the Connection store nicely, and gives you a MonitorService for it for free :)

Somewhat similar to what I've done for the local case [here](https://github.com/ligato/networkservicemesh/pull/521)

**Comment by haiodo** [comment]
Since PR is merged, this one could be closed.

**Comment by edwarnicke** [comment]
Closed in #522
