### ISSUE TITLE
Investigate in-pod authentication

### ISSUE THREAD

**Issue by mestery** [ligato/networkservicemesh#53]
The review for #46 indicated a desire to explore in-pod authentication. This issue tracks that investigation.

**Comment by prateekgogia** [comment]
@mestery  Can we can close this?

**Comment by mestery** [comment]
Was this implemented as part of #67? If so, yes, lets close it.

**Comment by prateekgogia** [comment]
Yes, #67 adds support for in-cluster authentication.
