### ISSUE TITLE
Add validators for CRDs

### ISSUE THREAD

**Issue by mestery** [ligato/networkservicemesh#57]
PR #54 adds in support for CRDs, but does not add in the validators into the CRD schemas. We'll likely want to take advantage of this functionality, so this issue will track adding that support.

**Comment by mestery** [comment]
@sbezverk Thanks for volunteering to take this one on! Here is what I think you want to validate:

* https://github.com/ligato/networkservicemesh/blob/master/pkg/apis/networkservicemesh.io/v1/types.go#L38
* https://github.com/ligato/networkservicemesh/blob/master/pkg/apis/networkservicemesh.io/v1/types.go#L64
* https://github.com/ligato/networkservicemesh/blob/master/pkg/apis/networkservicemesh.io/v1/types.go#L90

**Comment by sbezverk** [comment]
@mestery I would like to confirm which level of validation you have envisioned, would you like to validate just the format of below fields(length/content) or some logic (both name and uuid must be present) etc.
if it is former then by just extending CRD definition with `validation by openAPIV3Schema`  it can be achieved, latter would require web-hooks.

```
message NetworkServiceEndpoint {
    string name = 1;
    string uuid = 2;
};

message NetworkService {
    string name = 1;
    string uuid = 2;
    string selector = 3;

    message NetmeshChannel {
        string name = 1;
        string payload = 2;
    };
    repeated NetmeshChannel channels = 4;
};
```
Appreciate your comments.

**Comment by mestery** [comment]
I was envisioning the former. Thanks!

**Comment by sbezverk** [comment]
@mestery 

```
type NetworkService struct {
	Name     string                           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Uuid     string                           `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
	Selector string                           `protobuf:"bytes,3,opt,name=selector" json:"selector,omitempty"`
	Channels []*NetworkService_NetmeshChannel `protobuf:"bytes,4,rep,name=channels" json:"channels,omitempty"`
}
```
It looks like none of the elements of NetworkService are required, is it by design? if it is, appreciate a comment why.
Also I could not find if you have any limitations which needs to be enforced. Should I use `k8s` common limits for names and uuid?
