### ISSUE TITLE
Support IP Neighbor entries in ConnectionContext

### ISSUE THREAD

**Issue by edwarnicke** [ligato/networkservicemesh#571]
This is an extension of #555 

Add to ConnectionContext an ```ConnectionContext.IpNeighbors []*IpNeighbor```
Where

```
message IpNeighbor {
   string ip = 1;
   string hardware_address = 2;
}
```

For the case of NSC's with MechanismType == KernelInterface, use [LinuxStaticArpEntries](https://github.com/ligato/vpp-agent/blob/v1.7/plugins/linux/model/l3/l3.proto#L50) to enter those IpNeighbor entries into the namespace of the NSC.

**Comment by haiodo** [comment]
Working solution in https://github.com/ligato/networkservicemesh/pull/559
