### ISSUE TITLE
Support ExtraPrefixes in ConnectionContext

### ISSUE THREAD

**Issue by edwarnicke** [ligato/networkservicemesh#572]
This is an extension of #555 and #571 

It is sometimes the case that an NSC will need a collection of prefixes for its own use from its upstream NSE.  In the ConnectionContext we might express this as:

```ConnectionContext.RequestExtraPrefixies []ExtraPrefixRequest``` to be set by the NSC
and
```ConnectionContext.ExtraPrefixes [] string``` to be set by the NSE.

```
message ExtraPrefixRequest {
    Af_family = 1;
    int prefix_len = 2;
    int required_number = 3;
    int requested_number =4;
}
```

For Af_family, simply copy [Family enum](https://github.com/ligato/vpp-agent/blob/v1.7/plugins/linux/model/l3/l3.proto#L72).  prefix_len is the length of the prefix (like /30 or /24).

I would suggest writing some validators to catch things like prefix_len exceeding the max allowable by af_family (/32 for ipv4, /128 for ipv6).  

It would also be super helpful to write a helper function:

```
func extract_prefixes(prefixes []string, requests[] ExtraPrefixRequest) (requested []string, remaining []string, _ 
 error)
```

If it is possible to carve out of the prefixes argument the requests, it returns those prefixes as requested and the remaining list of prefixes.  If not, an error.

Some details.  A prefix can be split into smaller pieces.  So if I have a prefix 10.10.1.0/24, and a request for a /32.  I can break that into a two /25s, break one of those /25s into two /26s, etc until I get down to a

```
/25, /26, /27 , /28, /29, /30, /31, and two /32s
```
You can visualize it as:
```
[/25,[/26,[/27,[/28,[/29,[/30,[/31,[/32,/32]]
``` 

Obviously, its desirable if you have to split a prefix to split the *smallest* prefix you have in order to meet the request.

Its also desireable to have a function:

```
func release_prefixes(current_prefixes []string, released_prefixes[]) prefixes []string
```
which should try to 'merge' the released_prefixes back into the current_prefixes.  So for example, if two /32's are turned adjacent to one /31 ... role them back up into a single /30.  The point being to try to have the most compact possible set of prefixes in the return.

As you are doing this, you may consider other helpful functions along the way, like merge_prefixes that could be used by others.

**Comment by platoff** [comment]
@edwarnicke do you have any test/verify scenario for this, please can you share it?

**Comment by haiodo** [comment]
It is cleat to me what to do, @platoff shared this task to me.

**Comment by edwarnicke** [comment]
@haiodo Perhaps an example.  Say I'm an NSE, that is also an NSC (like the Firewall Pod).

I believe I need minimally 5 /24 prefixes.  But I'd rather have 10 /24 prefixes.  If I don't get 5, I can't function.

So required_number = 5, requested_number = 10. 

If the NSE I am trying to connect to can only do 3 /24 prefixes, it should reject my request, as it can't give me the required number of prefixes.  

If the NSE I am connecting to can do 7 /24 prefixes, it may choose to give me 7, since I 'requested' 10, but it wouldn't reject my request because I only 'require' 5.

If the NSE I am connecting to can do 25 /24 prefixes, it may choose to give me at most 10, because I only requested 10.

Make sense?

**Comment by haiodo** [comment]
Yes, Thanks clear now.

**Comment by nickolaev** [comment]
After merging #642 and #645 this one is completed. Closing. Please reopen in case something else is needed.
