### ISSUE TITLE
Introduce the NSM SDK

### ISSUE THREAD

**Issue by nickolaev** [ligato/networkservicemesh#611]
To foster the adoption of NSM within the CNF builders community we might wish to implement a stable API/SDK which will allow them to plug to NSM without knowing or caring about NSM's details.

I'm sharing here my thoughts, but would like to use this issue as a communication platform to come to a common understanding of where we want to go.

A list of the desired common SDK features:
 * currently Go, but probably worth looking into exposing the functionality to the C/C++ world too (_-buildmode=c-shared_)
 * a single package to import
 * APIs to Create an NSM client with the following properties
   * desired **MechanismType**
   * optional **InterfaceUp** callback
   * optional **InderfaceDown** callback
   * A single application may request _multiple connections_ to the same or different NSE

 * APIs to create an NSM endpoint with the following properties
   * desired **MechanismType**
   * **NewConnectionRequest** callback
   * **CloseConnection** callback
   * multiple NSEs per application (do we want that?)

 * A mechanism to enable NS endpoint + client functionality. In this scenario, the application will set the global NS name and the advertised labels, as well as the downstream connect labels.
  * The NS name is the NetworkService that the app will belong to, e.g. `secure-intranet-connectivity`. This will be the same name advertised for the Endpoint and used for the next service Client.
  * The labels that the application advertises describe its capabilities and specifics. Could be 'app=firewall' but also 'app=firewall,region=east'

Ideally, the SDK should allow for seamless Connection "liveliness" monitoring and potentially Connection autohealing (i.e. if the connection to the NSE goes down for some reason, go and find me a new one).

**Comment by nickolaev** [comment]
I have started some work in https://github.com/ligato/networkservicemesh/pull/604, but it si far from complete for now.

**Comment by haiodo** [comment]
+ point from me, right now NSE uses NSMDp with RequestConnection and this allocate workspace, we need to think about having this "unix-socket" way optional to allow NSC/NSE connecting to NSM via tcp. As @edwarnicke @fkautz shown on deep dive NSE could be outside of kubernetes.

**Comment by fkautz** [comment]
For the client, we should probably take in a ```grpc.ClientConn```

For the server, this is the initialization example:

```go
lis, err := net.Listen("tcp", fmt.Sprintf(":%d", *port))
if err != nil {
        log.Fatalf("failed to listen: %v", err)
}
grpcServer := grpc.NewServer()
```

We should determine whether we want to receive a ```net.Listener``` or a ```grpc.Server```

**Comment by edwarnicke** [comment]
@haiodo The good news is, from the NSE point of view, it basically just sees some ENV variables for what to connect to.  We could shift that a bit to unix:${filename} or tcp:${ip addr} in those ENV variables and I *think* that gets the flexibility you are looking for :)

**Comment by edwarnicke** [comment]
@haiodo And the 'workspace' env variable can be made to point to any appropriate place for the memif sockets etc.

**Comment by edwarnicke** [comment]
@haiodo Also begs the question as to whether we want the SDK to provide tools/patterns for writing unit tests for NSEs... I suspect so.

**Comment by edwarnicke** [comment]
@nickolaev Can we close this issue?

**Comment by nickolaev** [comment]
#604 merged. Closing.
