### ISSUE TITLE
Update Docs on Build and deploy to make clearer

### ISSUE THREAD

**Issue by quangtamle** [ligato/networkservicemesh#616]
Hello everyone,

I am starting to using Network Service Mesh. When I tried to running NSM on a Kubernetes cluster in Vagrant, I faced this issue: 

" worker: [discovery] Failed to request cluster info, will try again: [Get https://172.28.128.3:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 172.28.128.3:6443: connect: connection refused]"

Have anyone face this issue like mine ??? and how could I fix it ???

Thank you in advance !!!

**Comment by nickolaev** [comment]
Welcome @quangtamle . Can you try the following set of commands:

```
make vagrant-restart
source scripts/vagrant/env.sh
make k8s-infra-deploy
make k8s-icmp-deploy
make k8s-check
```

You can find more details here:
https://github.com/ligato/networkservicemesh/blob/master/docs/BUILD.md#having-more-control-on-the-deployment

Hope that helps.

**Comment by edwarnicke** [comment]
One other (possibly under documented) step:
eval "$(${GOPATH}/github.com/ligato/networkservicemesh/scripts/vagrant/env.sh)"

This sets the KUBECONFIG env variable to point to where the kubeconfig gets set.

**Comment by quangtamle** [comment]
Dear @nickolaev , @edwarnicke 

Thank you so much for your instructions !!! it works now

But after that there is another problem come up which is that i can not ssh to the k8s-master or k8s-worker or even show the "vagrant-status".
![screenshot from 2018-12-18 15-38-20](https://user-images.githubusercontent.com/43220759/50161969-71b18c80-02dd-11e9-827a-e44e94831a6e.png)

How can i fix it ???

Thank you in advance!!!

**Comment by edwarnicke** [comment]
@quangtamle OK, looks like a couple of things are happening there:

1.  You don't appear to have kubectl installed on your host.  [Instructions for installing Kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/).  This is why your make command fails.
2. When you go to run vagrant commands, you need to run them in the directory that contains the Vagrantfile (./scripts/vagrant)

By the way... you are being super helpful in helping us learn things we can use to improve our documentation.  Thank you so much for filing the issue and sticking with us here :)

**Comment by quangtamle** [comment]
Dear @edwarnicke 

Thank you so much for your instructions !!!

1. Do I need to install kubectl in ubuntu host (i dont know because i am learning about NSM) ??? but i think we only need to install kubectl in master node and worker node. Am i right ??? the picture below shows what i meant.

2. It works perfectly !!! so now i can play with it

![screenshot from 2018-12-18 16-22-12](https://user-images.githubusercontent.com/43220759/50164341-b855b580-02e2-11e9-8283-1b1c76a65d94.png)
[](url)

Best regards

**Comment by edwarnicke** [comment]
@quangtamle Learning is good :)  We want to make this all super easy for folks.

The make machinery for networkservicemesh uses kubectl to drive your K8s Cluster (in this case, the one in vagrant).  So kubectl needs to be installed where ever the make machinery is being run (usually the host).

Note that kubectl is just a CLI that is able to talk remotely to whatever K8s cluster you point it to :)

**Comment by quangtamle** [comment]
Dear @edwarnicke 

Thank you so much for your detailed explaination !!! i learn lot of things from this

Best regards !

**Comment by edwarnicke** [comment]
@quangtamle So are you set then?

@nickolaev Should we turn this into a doc issue to track updating the docs ?

**Comment by nickolaev** [comment]
@edwarnicke I agree - we can use this to update the docs to be more explicit.

**Comment by quangtamle** [comment]
Dear @edwarnicke 

Everthing is fine until now !!! Thank you so much
