### ISSUE TITLE
Property handle Close() on  NSMD.

### ISSUE THREAD

**Issue by haiodo** [ligato/networkservicemesh#617]
We need to handle Close() properly in both Local and Remote NSMD implementation.

**Comment by haiodo** [comment]
+ We need integration tests to check if NSC Close() request causes a proper Routes/ARP entries/ interfaces shutdown.

**Comment by edwarnicke** [comment]
👍

**Comment by edwarnicke** [comment]
@haiodo As a side note here, I'm fine with doing this in a followup PR to #559 ... #559 has gotten way to big, and I'd like to merge it as soon as I can wrap my head around the source thing.
