### ISSUE TITLE
Use specific nsmd name in Jaeger UI

### ISSUE THREAD

**Issue by matrohon** [ligato/networkservicemesh#660]
Currently, jaeger traces display nsmd to nsmd grpc communication. It would be nice to differentiate the two nsmd that comunicate, for readability. May be we can use 'nsmd-hostname' instead of nsmd?

**Comment by edwarnicke** [comment]
@matrohon Can I close this now that #661 has gone in?

**Comment by matrohon** [comment]
It's fine now, names are more specific, and it's easier and faster to differentiate components. It's really convenient, thanks @platoff
