### ISSUE TITLE
Add readiness and liveness probes into Network Service Mesh

### ISSUE THREAD

**Issue by mestery** [ligato/networkservicemesh#92]
From a discussion over IRC, we should add these as we can prevent the pod from progressing to a ready state until NSM is ready. For example, until CRDs are registered and ready. Also, we can fail a pod faster if these probes become unresponsive. See below for a link to these:

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-readiness-probes

**Comment by fkautz** [comment]
Readiness probes prevent traffic until the pod is ready.

Liveness probes kill a pod if the pod becomes unresponsive to the probe.

We should have both.

**Comment by sbezverk** [comment]
Are you expecting then something like that:
1. Init container creates CRDs definitions
2. Liveness probe detects the time when CRDs becomes available in API
3. Main application starts?

If it is the case then creating CRD's needs to be moved out of a main application. Appreciate your thoughts.

**Comment by edwarnicke** [comment]
@nickolaev I would say the issue is more to make sure that we are robust to startup timing issues.

See #493 for example
