### ISSUE TITLE
Verify the ability to change the CNI driver in a Minikube

### ISSUE THREAD

**Issue by mestery** [ligato/networkservicemesh#96]
This came out of the 2018-06-01 weekly NSM meeting. We want to see if it's possible to change the CNI driver inside of a qinikube. Useful for testing and CI purposes.

**Comment by prateekgogia** [comment]
I looked into this, looks like minikube does support installing CNI plugins. I was able to install Calico plugin. Also, latest version of minikube 0.28 has a bug, which doesn’t let you start minikube with CNI enabled https://github.com/kubernetes/minikube/issues/2828 , I was able to get this working with an older version 0.22 following this comment - https://github.com/projectcalico/calico/issues/1013#issuecomment-325689943

**Comment by prateekgogia** [comment]
On Minikube node- 
```
kubectl get pods --all-namespaces
NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE
kube-system   calico-etcd-wjpgt                          1/1       Running   0          1m
kube-system   calico-node-s1mw3                          2/2       Running   0          1m
kube-system   calico-policy-controller-336633499-j9j23   1/1       Running   0          1m
kube-system   kube-addon-manager-minikube                1/1       Running   0          2m
kube-system   kube-dns-910330662-4l368                   3/3       Running   0          2m
kube-system   kubernetes-dashboard-36hv5                 1/1       Running   0          2m
```

**Comment by mestery** [comment]
Thanks for verifying @prateekgogia! I think we can close this one. Also worth noting that I'm running with Minikube v0.25 because I hit an issue with anything newer. Can't recall what that issue was, but v0.25 seems to work fine.

**Comment by fkautz** [comment]
Before we close this, I'd like to get some documentation written up in docs/ stating this information.
